openapi: 3.0.0
info:
  version: '1.0'
  title: OfercompasAPI
  description: API para el servicio de Ofercompas

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/EfrainCami/Ofercompas/1.0

paths:
  /ofertas:
    get:
      summary: Devuelve una lista de ofertas
      parameters:
        - name: numeroPagina
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
        - name: categoria
          in: query
          required: false
          schema:
            type: string
            minLength: 1
            maxLength: 20
        - name: calificacionMinima
          in: query
          required: false
          schema:
            type: integer

      responses:
        '200':
            description: Un arreglo JSon de Ofertas
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    pedidos:
                      type: array
                      items:
                        $ref: '#/components/schemas/OfertaSchema'

    post:
      summary: Publica una oferta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfertaSchema'
      responses:
        '201':
            description: Una representación JSON de la oferta creada
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/OfertaSchema'

  /ofertas/{id_oferta}:
    parameters:
      - in: path
        name: id_oferta
        required: true
        schema:
          type: string
    get:
      summary: Devuelve los detalles de una oferta específica
      responses:
        '200':
          description: Una representación JSON de una oferta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfertaSchema'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Actualiza una oferta existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfertaSchema'
      responses:
        '200':
          description: Una representación JSON de una oferta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfertaSchema'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Elimina una oferta existente
      responses:
        '204':
          description: El recurso se eliminó con éxito

  /miembros:
    post:
      summary: Registra un miembroOfercompas en la comunidad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MiembroOfercompasSchema'
      responses:
        '201':
          description: Una representación JSON del miembroOfercompasRegistrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MiembroOfercompasSchema'
        '400':
            $ref: '#/components/responses/BadRequest'

  /miembros/{emailMiembro}:
    put:
      summary: Actualiza un Miembro Ofercompas existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MiembroOfercompasSchema'
      responses:
        '200':
          description: Una representación JSON del Miembro Ofercompas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MiembroOfercompasSchema'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Cambia el atributo estaActivo de un miembroOfercompas a false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MiembroOfercompasSchema'
      responses:
        '200':
          description: Una representación JSON del Miembro Ofercompas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MiembroOfercompasSchema'
        '404':
          $ref: '#/components/responses/NotFound'


components:
  responses:
    Success:
      description: Solicitud realizada con exito

    NotFound:
      description: No se encontró el recurso especificado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: El servidor no pudo interpretar la solicitud, sintaxis invalida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string

    PublicacionSchema:
      type: object
      required:
        - titulo
        - descripcion
        - puntuacion
        - estadoPublicacion
        - categoria
      properties:
        titulo:
          type: string
          description: Titulo de la oferta
          example: Raspberry pi 3 firmada por Efra
        descripcion:
          type: string
          description: Descripcion de la publicacion
          example: Una raspberry pi firmada por Efrain Roblox Pro Player
        puntuacion:
          type: integer
          description: Pustuacion de la publicacion
          minimum: -999
          maximum: 999
          example: 12
        estadoPublicacion:
          type: string
          enum:
            - ACTIVA
            - TERMINADA
            - PROHIBIDA
            - ELIMINADA
        categoria:
          type: string
          enum:
            - TECNOLOGIA
            - MODA_MUJER
            - MODA_HOMBRE
            - HOGAR
            - MASCOTAS
            - VIAJE
            - ENTRETENIMIENTO
            - COMIDA_BEBIDA

    OfertaSchema:
      allOf:
        - $ref: '#/components/schemas/PublicacionSchema'
        - type: object
          required:
            - precio
            - vinculo
          properties:
            precio:
              type: integer
              description: Precio en pesos del producto incluyendo centavos
              format: float
              example: 500.50
            vinculo:
              type: string
              description: Link que lleva al sitio de la oferta
              example: https://articulo.mercadolibre.com.mx/MLM-756165002-raspberry-pi4-4gb-case-ventilador-sd-32gb-hdmi-pi-4-b-kit




    MiembroOfercompasSchema:
      type: object
      required:
        - nickname
        - email
        - contrasenia
        - estadoMiembro
        - tipoMiembro
      properties:
        nickname:
          type: string
          description: Nombre identificador unico de cada Miembro
          example: YiraPvP
        email:
          type: string
          format: email
          description: Correo electronico del miembro
          example: rendon.luisgerardo@gmail.com
        contraenia:
          type: string
          description: Contrasenia de acceso del usuario
          example: YiraTheBest
        estadoMiembro:
          type: string
          description: Posibles estados que toma el Miembro en el sistema
          enum:
            - ACTIVO
            - EXPULSADO
            - ELIMINADO
          example: ACTIVO
        tipoMiembro:
          type: string
          description: Los tipos de roles que un Miembro puede cumplir en el sistema
          enum:
            - COMUN
            - MODERADOR
            - ADMINISTRADOR
          example: COMUN

    DenunciaSchema:

